name: "Pull Request Labels: develop"

on:
  pull_request_target:
    types: [opened]
    branches:
      - develop

jobs:
  pr_label_develop:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/lc-labels.yml
