name: "Pull Request Labels: LC*"

on:
  pull_request_target:
    types: [opened]
    branches:
      - "LC**"

jobs:
  pr_label_lc:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/lc-labels.yml
