name: "Pull Request Labels: main"

on:
  pull_request_target:
    types: [opened]
    branches:
      - main

jobs:
  pr_label_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.LABELER_TOKEN }}"
        configuration-path: .github/main-labels.yml
